[build]
  command = "npm run generate"
  publish = "dist"

[context.deploy-preview]
  command = "npm run build"

[template.environment]
  IBL_PAGE_TITLE = "Infinity Bots Blog"
  IBL_COMPANY_LOGO = "url to your company's logo"
  IBL_SUPPORT_CONTACT_LINK = "https://infinitybotlist.com/discord"
